# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://wowchemy.com/docs/guide/language/

# Default language
pl:
  languageCode: pl-pl
  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  contentDir: content/pl

# Uncomment the lines below to configure your website in a second language.
nl:
  languageCode: nl-nl
  contentDir: content/nl
  title: Poolse School Nijmegen
#  params:
#    description: Site description in Chinese...
#  menu:
#    main:
#      - name: Voorbeeld
#        url: '#about'
#        weight: 1
