# SITE SETUP
# Guide: https://wowchemy.com/docs/getting-started/
# Documentation: https://wowchemy.com/docs/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance

theme: 'nijmegenps'
day_night: false
font: 'minimal'
font_size: L

# SEO

site_type: Organization
local_business_type: ''
org_name: 'Vereniging Poolse School Nijmegen – Arnhem'
description: ''
twitter: ''

# Contact (edit or remove options as required)
# Public Elementary School de Tarthorst
# Tarthorst 4, 6708 HH Wageningen

email: polskaszkolanijmegen@gmail.com
# phone: 888 888 88 88
address:
  street: 'Vereniging Poolse School Nijmegen – Arnhem<br>Nijenkamp 141'
  city: Druten
  region: 'Gelderland'
  postcode: '6651 HJ'
  country: Nederland
  country_code: NL
coordinates:
  longitude: '' # '5.66098'
  latitude: '' # '51.97864'
directions: |-
  - <a href="https://www.openstreetmap.org/directions?engine=osrm_car&route=51.97864,5.66098#map=18/51.97864/5.66098&layers=N" target="_blank">Kierunki lokalizacja szkoły</a>
  - <a href="https://www.openstreetmap.org/directions?engine=osrm_car&route=51.97864,5.66098#map=18/51.97864/5.66098&layers=N" target="_blank">Routebeschrijving school locatie</a>
office_hours:
  - 'Dwa razy w miesiącu, w soboty od godziny 10.45 do godziny 13.30'
  - 'Tweemaal per maand, op zaterdag van 10:45u-13:30u'
# appointment_url: '/calendar/'
contact_links:
  - icon: piggy-bank
    icon-pack: facebook-square
    name: |-
      - Konto bankowe: __NL41 SNSB 0902746022__ t.n.v __Vereniging Poolse School Nijmegen__
      - Bankrekening:  __NL41 SNSB 0902746022__ t.n.v __Vereniging Poolse School Nijmegen__
    link: '/contact'
  - icon: facebook-square
    icon_pack: fab
    name: Facebook Polska Szkoła Nijmegen – Arnhem
    link: 'https://www.facebook.com/polskaszkolanijmegen/'
  # - icon: skype
  #   icon_pack: fab
  #   name: Skype Me
  #   link: 'skype:echo123?call'
  # - icon: keybase
  #   icon_pack: fab
  #   name: Chat on Keybase
  #   link: 'https://keybase.io/'
  # - icon: comments
  #   icon_pack: fas
  #   name: Discuss on Forum
  #   link: 'https://discourse.gohugo.io'

# Site header

main_menu:
  enable: true
  align: r
  show_logo: true
  show_language: true
  show_day_night: true
  show_search: true
  highlight_active_link: true

# Localization

date_format: 'Monday, 02 Jan 2006'
time_format: '15:04'
address_format: nl-nl

# Site features

highlight: true
highlight_languages:
  - r
  - python
  - latex
math: false
diagram: false
privacy_pack: false
edit_page:
  repo_url: ''
  content_dir: ''
  repo_branch: main
  editable:
    page: false
    post: false
    book: false
show_related:
  book: true
  page: false
  post: true
  project: true
  publication: true
  event: true
reading_time: true
section_pager: false
docs_section_pager: true
sharing: true
copyright_license:
  enable: false
  allow_derivatives: false
  share_alike: true
  allow_commercial: false
  notice: 'This work is licensed under {license}'
abstract_length: 135
plugins_js: []
avatar:
  gravatar: false
  shape: circle
publications:
  date_format: January 2006
  citation_style: apa
projects:
  post_view: 2
  publication_view: 2
  talk_view: 2
breadcrumb:
  page_types:
    book: true
comments:
  provider: ''
  commentable:
    post: true
    book: true
    project: true
    publication: true
    event: true
  disqus:
    shortname: ''
    show_count: true
  commento:
    url: ''
search:
  provider: wowchemy
  algolia:
    app_id: ''
    api_key: ''
    index_name: ''
    show_logo: false
map:
  provider: mapnik
  api_key: ''
  zoom: 18
marketing:
  google_analytics: ''
  google_tag_manager: ''
  google_site_verification: ''
  baidu_site_verification: ''
  baidu_tongji: ''
cms:
  branch: master
  local_backend: false
icon:
  pack:
    ai: false
